# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  ...
}: let
  wan = "eth0";
in {
  boot = {
    initrd.availableKernelModules = ["nvme" "ahci"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  networking = {
    useDHCP = lib.mkDefault false;
    # ── IPv4 ───────────────────────────────────────────────
    interfaces.${wan} = {
      ipv4.addresses = [
        # Main public address, /26 netmask (255.255.255.192)
        {
          address = "162.55.238.233";
          prefixLength = 26;
        }
      ];

      # Default route via the subnet gateway
      ipv4.routes = [
        {
          address = "0.0.0.0";
          prefixLength = 0;
          via = "162.55.238.193";
        }
      ];

      # ── IPv6 ─────────────────────────────────────────────
      ipv6.addresses = [
        # First usable address in your /64; feel free to pick another host ID
        {
          address = "2a01:4f8:271:404a::1";
          prefixLength = 64;
        }
      ];
    };

    defaultGateway = "162.55.238.193";
    # Hetzner’s switch link‑local gateway for IPv6
    defaultGateway6 = {
      address = "fe80::1";
      interface = wan;
    };

    nameservers = ["185.12.64.1" "185.12.64.2"]; # Hetzner public DNS
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
