name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main, deploy-rs]

permissions:
  contents: read
  checks: write

# one in progress and one in queue
# newest pipeline replaces the queued pipeline
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  prepare:
    name: Find NixOS Configurations 🔍
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup SSH for private repository
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SECRETS_REPO_SSH_KEY }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Find NixOS Configurations 🔍
        id: matrix
        run: |
          nix eval --json .#nixosConfigurations --apply '
            configs:
            builtins.map (name: {
              configuration = name;
            }) (builtins.attrNames configs)
          ' | perl -pe 's|(.*)|matrix=\1|' >>$GITHUB_OUTPUT

  deploy:
    name: Deploy NixOS Configuration (${{ matrix.configuration }})🚀
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: ${{ matrix.configuration }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: docker/setup-qemu-action@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: Setup SSH for private repository
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy
        run: nix run nixpkgs#deploy-rs -- .#${{ matrix.configuration }} --skip-checks --remote-build
