name: Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  checks: write

# one in progress and one in queue
# newest pipeline replaces the queued pipeline
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy NixOS Configuration 🚀
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    environment: everything
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: docker/setup-qemu-action@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            substituters = https://cache.nixos.org https://cache.walawren.com
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= kiriwalawrencache:CqHekzeXjrGlnq4FKlnOQQGlNvnzDzhCbvOthomGRTU=

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: kiriwalawren
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          nix build --print-build-logs .#cachix-deploy-spec
          nix path-info --recursive ./result | xargs cachix push kiriwalawren
          cachix deploy activate ./result
